name: flutter_qiblah
description: Flutter Qiblah is a package that allows you to display Qiblah direction in you app with support for both Android and iOS
version: 3.1.0+1
homepage: https://github.com/medyas/flutter_qiblah

environment:
  sdk: ">=3.0.0 <4.0.0"

  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_compass_v2: ^1.0.3
  geolocator: ^14.0.2
  stream_transform: ^2.1.1
  vector_math: ^2.1.4

flutter:
  plugin:
    platforms:
      android:
        package: ml.medyas.flutter_qiblah
        pluginClass: FlutterQiblahPlugin
      ios:
        pluginClass: FlutterQiblahPlugin
