name: flutter_qiblah
description: Flutter Qiblah is a package that allows you to display Qiblah direction in you app with support for both Android and iOS
version: 2.1.0
homepage: https://github.com/medyas/flutter_qiblah

environment:
  sdk: ">=2.15.0 <3.0.0"

  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_compass: ^0.7.0
  geolocator: ^9.0.2
  stream_transform: ^2.0.1
  vector_math: ^2.1.2

flutter:
  plugin:
    platforms:
      android:
        package: ml.medyas.flutter_qiblah
        pluginClass: FlutterQiblahPlugin
      ios:
        pluginClass: FlutterQiblahPlugin
